#!/usr/bin/env python3
"""Build self-contained Klipper configs from the ordered modular sources.

Uses only the Python standard library. Run from any directory; no printer,
network access or installed Klipper is required. This builds files, not an
installer: it never edits printer.cfg or restarts anything.
"""
import argparse
import configparser
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGETS = ("svzero-1.3.7.cfg", "svzero-1.4.x.cfg", "svzero-python.cfg")


def digest(data):
    return hashlib.sha256(data).hexdigest()


def expand(root, relative, inputs, stack=()):
    """Expand explicit includes in place, retaining later section overrides.

    Wildcards are intentionally unsupported: release contents must not depend
    on an unlisted optional or personal file appearing in the source directory.
    """
    path = root / relative
    if path.is_symlink() or any(p.is_symlink() for p in path.parents if p != root):
        raise ValueError("Symlink source refused: " + str(relative))
    if not path.resolve().is_relative_to(root):
        raise ValueError("Include outside source root: " + str(relative))
    name = path.relative_to(root).as_posix()
    if name in stack:
        raise ValueError("Include cycle: " + " -> ".join((*stack, name)))
    if not path.is_file():
        raise ValueError("Missing include: " + name)
    data = path.read_bytes()
    inputs[name] = digest(data)
    lines = ["\n# BEGIN SOURCE: " + name + "\n"]
    for line in data.decode("utf-8").splitlines(keepends=True):
        # Klipper strips # comments before recognizing include headers.
        match = configparser.RawConfigParser.SECTCRE.match(line.split("#", 1)[0])
        section = match.group("header") if match else ""
        if section.startswith("include "):
            child = section[8:].strip()
            if not child or any(c in child for c in "*?["):
                raise ValueError("Include must name one explicit file: " + name)
            child_path = Path(child)
            if child_path.is_absolute() or ".." in child_path.parts:
                raise ValueError("Unsafe include path in " + name)
            lines.append(expand(root, Path(name).parent / child_path, inputs, (*stack, name)))
        else:
            lines.append(line)
    lines.append("\n# END SOURCE: " + name + "\n")
    return "".join(lines)


def render(root):
    root = root.resolve()
    outputs, manifest = {}, {"format": 1, "targets": {}}
    for target in TARGETS:
        inputs = {}
        body = expand(root, Path(target), inputs)
        if target == "svzero-python.cfg":
            instructions = (
                "# OPTIONAL: adaptive preheat and Spoolman. Install chamber_preheat.py,\n"
                "# spool_guard.py and moonraker.py into klippy/extras before enabling.\n"
                "# Include AFTER the firmware file. See INSTALL.md for service restart.\n")
        else:
            instructions = (
                "# Native macros only; no optional Python modules are required.\n"
                "# Include after stock macros and hardware, before SAVE_CONFIG.\n")
            if target == "svzero-1.4.x.cfg":
                instructions += (
                    "# FIRST disable the entire stock [temperature_fan exhaust_fan]\n"
                    "# section. Keep [fan_generic fan3]. See INSTALL.md for rollback.\n")
        header = (
            "# GENERATED by tools/build-macros.py. Edit the separate source files.\n"
            "# Copy this file to printer_data/config/svzero/ and add to printer.cfg:\n"
            "# [include svzero/" + target + "]\n"
            + instructions
            + "# Do not include the modular sources as well. Restart only while idle.\n"
            "# Source comments below describe the modular development layout.\n")
        outputs[target] = (header + body).encode("utf-8")
        manifest["targets"][target] = {
            "sources": dict(sorted(inputs.items())),
            "sha256": digest(outputs[target]),
        }
    outputs["manifest.json"] = (json.dumps(manifest, indent=2) + "\n").encode("utf-8")
    return outputs


def build(root=ROOT, output=None, check=False):
    root = Path(root).resolve()
    output = Path(output) if output is not None else root / "bundles/klipper"
    if output.is_symlink():
        raise ValueError("Symlink output directory refused")
    output = output.resolve()
    outputs = render(root)
    inputs = {root / name for target in json.loads(outputs["manifest.json"])["targets"].values()
              for name in target["sources"]}
    for name in outputs:
        path = output / name
        if path.is_symlink() or path in inputs:
            raise ValueError("Output would overwrite a source or symlink: " + name)
    if check:
        stale = [name for name, data in outputs.items()
                 if not (output / name).is_file() or (output / name).read_bytes() != data]
        if stale:
            raise ValueError("Rebuild macro bundles: " + ", ".join(stale))
    else:
        output.mkdir(parents=True, exist_ok=True)
        for name, data in outputs.items():
            (output / name).write_bytes(data)
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="Output directory (default: bundles/klipper)")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are missing or stale")
    args = parser.parse_args()
    try:
        outputs = build(output=args.output, check=args.check)
    except ValueError as error:
        parser.exit(1, str(error) + "\n")
    print(("Checked" if args.check else "Built") + " 3 self-contained configs and source checksum manifest")


if __name__ == "__main__":
    main()
